apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: third-ingress
spec:
  rules:
  - http:
      paths:
      - path: /third
        pathType: Prefix
        backend:
          service:
            name: third
            port:
              number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: third
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: third
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "third-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "third-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "third-service.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "third-service.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: third
          image: jimaandron/flask-hello:latest
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: MESSAGE
              value: "{{ .Values.message }}"
          resources:
            limits:
              cpu: "{{ .Values.cpuLimit }}"
              memory: "{{ .Values.memoryLimit }}"

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: third-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: third
  minReplicas: 1
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80

